import type { Product } from './products'
import { Pinecone } from '@pinecone-database/pinecone'

type StoredVector = {
  id: string
  values: number[]
  metadata?: Record<string, unknown>
}

declare global {
  var __localProductVectors: Record<string, StoredVector> | undefined
  var __pineconeClient: Pinecone | undefined
}

// In-memory fallback store
function ensureLocalStore() {
  if (!global.__localProductVectors) global.__localProductVectors = {}
  return global.__localProductVectors
}

// Pinecone client initialization
function getPineconeClient() {
  if (!process.env.PINECONE_API_KEY || !process.env.PINECONE_INDEX_NAME) {
    console.warn('⚠️ Pinecone credentials missing, using in-memory store')
    return null
  }

  if (!global.__pineconeClient) {
    global.__pineconeClient = new Pinecone({
      apiKey: process.env.PINECONE_API_KEY
    })
  }
  return global.__pineconeClient
}

export const productIndex = {
  async upsert(vectors: StoredVector[]) {
    const client = getPineconeClient()
    
    if (!client || !process.env.PINECONE_INDEX_NAME) {
      // Fallback: use in-memory store
      const store = ensureLocalStore()
      for (const v of vectors) store[v.id] = v
      console.log(`✅ Upserted ${vectors.length} vectors (in-memory)`)
      return { upsertedCount: vectors.length }
    }

    try {
      const index = client.Index(process.env.PINECONE_INDEX_NAME)
      const records = vectors.map(v => ({
        id: v.id,
        values: v.values,
        metadata: v.metadata || {}
      }))
      
      await index.upsert(records as unknown as Parameters<typeof index.upsert>[0])
      console.log(`✅ Upserted ${vectors.length} vectors to Pinecone`)
      return { upsertedCount: vectors.length }
    } catch (e) {
      console.error('❌ Pinecone upsert failed:', e)
      // Fallback to in-memory
      const store = ensureLocalStore()
      for (const v of vectors) store[v.id] = v
      return { upsertedCount: vectors.length }
    }
  },

  async query({ vector, topK = 6 }: { vector: number[]; topK?: number }) {
    const client = getPineconeClient()
    
    if (!client || !process.env.PINECONE_INDEX_NAME) {
      // Fallback: use in-memory store
      return queryLocalStore(vector, topK)
    }

    try {
      const index = client.Index(process.env.PINECONE_INDEX_NAME)
      const results = await index.query({
        vector,
        topK,
        includeMetadata: true
      })
      
      return {
        matches: results.matches?.map(m => ({
          id: m.id,
          score: m.score || 0,
          metadata: m.metadata
        })) || []
      }
    } catch (e) {
      console.error('❌ Pinecone query failed:', e)
      // Fallback to in-memory
      return queryLocalStore(vector, topK)
    }
  }
}

function queryLocalStore(vector: number[], topK = 6) {
  const store = ensureLocalStore()
  const items = Object.values(store)
  
  function dot(a: number[], b: number[]) {
    return a.reduce((s, v, i) => s + v * (b[i] ?? 0), 0)
  }
  
  function norm(a: number[]) {
    return Math.sqrt(a.reduce((s, v) => s + v * v, 0))
  }
  
  const qnorm = norm(vector)
  const scored = items.map(item => {
    const score = qnorm === 0 || norm(item.values) === 0 ? 0 : dot(vector, item.values) / (qnorm * norm(item.values))
    return { id: item.id, score, metadata: item.metadata }
  })
  
  scored.sort((a, b) => b.score - a.score)
  return { matches: scored.slice(0, topK) }
}

export async function seedProducts(products: Product[]) {
  const vectors = await Promise.all(products.map(async (p) => {
    // Placeholder values; real embeddings should be generated by OpenAI
    return {
      id: String(p.id),
      values: new Array(1536).fill(0.001), // OpenAI embedding dimension: 1536
      metadata: {
        name: p.name,
        base_price_paisa: p.base_price_paisa,
        emoji: p.emoji
      }
    }
  }))
  
  await productIndex.upsert(vectors)
  console.log(`🌱 Seeded ${vectors.length} products`)
}
